/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_Demo */

#ifndef _Included_demo_Demo
#define _Included_demo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_Demo
 * Method:    get_hoop_position
 * Signature: (ILjava/lang/String;Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_demo_Demo_get_1hoop_1position
  (JNIEnv *, jobject, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
